### ISSUE TITLE
Handling for invalid UTF8 characters in headers

### ISSUE THREAD

**Issue by natl** [eyurtsev/fcsparser#7]
I'm working with FCS2 files from a CellQuest Pro 6 cytometer, and I've found that the machine puts the non-UTF8 character \xaa in the header file next to the machine name. I get around this by removing the non-unicode character before reading the file with FCSparser, but would you be open to changing line 166 in api.py from
```.py
 raw_text = raw_text.decode('utf-8')
```
to
```.py
 raw_text = raw_text.decode('utf-8', errors='ignore')
```
Let me know if you want me to submit a pull request for the change?
-Nathanael

**Comment by eyurtsev** [comment]
A PR would be appreciated. :)

Maybe do the following:

```
try: 
  raw_text = raw_text.decode('utf-8')
except UnicodeDecodeError as e:  #6 (or whatever it's called)
  raw_text = raw_text.decode('utf-8', errors='ignore')
  warning.warn(warning message + some information from e)
```

**Comment by natl** [comment]
Good point. I'll have a PR for you in a day or two. Thanks.

**Comment by eyurtsev** [comment]
Thanks! sorry for the delay in merging
