### ISSUE TITLE
fcsparser added to conda-forge

### ISSUE THREAD

**Issue by aliciaaevans** [eyurtsev/fcsparser#72]
I see that fcsparser was recently added to conda-forge by @berombau. Once something is added to Conda-forge, we usually remove it from Bioconda. Often, that happens because a package is for generic use and not bioinformatics-specific. Since this is bio related and the Readme here includes instructions to install from bioconda, before I remove the recipe from Bioconda, I just want to check with @eyurtsev 

https://github.com/conda-forge/staged-recipes/pull/26252
https://github.com/conda-forge/fcsparser-feedstock 
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fcsparser/meta.yaml

**Comment by eyurtsev** [comment]
Hi @aliciaaevans! Thanks for checking in! I've never used conda personally, so I'm ignorant about how the conda ecosystem works. What action is required of me? Will any dependent packages be affected?

**Comment by aliciaaevans** [comment]
It's more a matter of preference. The easiest thing since it's already in conda-forge would be to remove the recipe from bioconda. Otherwise, someone from the conda-forge team may have to get involved to back out the change. (There is a lint rule in place that was triggered in the PR to avoid this scenario, but I'm not sure why that was overlooked.) If you wanted to add a dependency to something in bioconda down the road, that could be a reason to keep it in bioconda and remove from conda-forge.

Since bioconda requires conda-forge channel to be configured anyway, I don't believe it should affect any dependent packages (unless someone was to hard-code the channel name in their dependencies which isn't supposed to be done). I can remove the recipe from the bioconda repo and all the older versions will remain in the bioconda channel but newer versions will end up in conda-forge (for the current version that is in both, conda-forge will take priority).

If you are OK with the move to conda-forge, then I suggest updating your readme to `conda install -c conda-forge fcsparser`.

**Comment by aliciaaevans** [comment]
Sounds good. Thanks!
